<a href="https://colab.research.google.com/github/Paoladevelopment/discretas2/blob/main/implementacionPunto1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#INSERTEN ACÁ SUS CÓDIGOS Y NOMBRES:
# Paola Andrea Domínguez Vélez, cod-> 2059956-3743
import numpy as np
import math

In [4]:
#Descripción: El siguiente pedazo de código implementa una clase llamada : "grafo". Donde se implementan
#los métodos correspondiente al grafo.

In [46]:
class grafo:
  def __init__(self, numVertices):
    self.numVertices= numVertices
    self.matrizAdyacencia= np.zeros((numVertices,numVertices))

#método de la clase que permitirá llenar la matriz de adyacencia del grafo con la información presente en la matriz
#del archivo

  def llenarMatriz(self, listaInfoArchivo):
    matrizAux= []
    for el in listaInfoArchivo:
      fila= [int(x) for x in el.split(' ')]
      matrizAux.append(fila)
    
    self.matrizAdyacencia= np.array(matrizAux)

#Descripción: Este método retorna la matriz de adyacencia con sus inf (infinitos) respectivos, para ayudarnos con el algoritmo de Warshall. 
#Los inf simbolizarán caminos no accesible entre par de vértices (es decir aquellos que no son adyacentes)

  def representacionWarshallMatriz(self):
    n= self.numVertices
    matriz_warshall= np.zeros((n,n))
    for i in range(n):
      for j in range(n):
        if(i!=j):
          if(self.matrizAdyacencia[i][j] == 0):
              matriz_warshall[i][j]= math.inf
          else: matriz_warshall[i][j]= self.matrizAdyacencia[i][j]
    return matriz_warshall

#Descripción: Este método se encarga de retornar la representacion de la matriz de camino inicial, es decir contendrá
#en sus filas el elemento de esa fila.

  def matrizCaminoInicial(self):
    n= self.numVertices
    matriz_caminoIni= np.zeros((n,n))
    for i in range(n):
      for j in range(n):
        if(i!=j):
          if(self.matrizAdyacencia[i][j] == 0):
              matriz_caminoIni[i][j]= -1
          else: matriz_caminoIni[i][j]= i
          
        else: matriz_caminoIni[i][j]= i
    return matriz_caminoIni

#Descripción:

  def algoritmoWarshall(self):
    #las siguientes matrices cambiarán sus valores= matriz_warshall & matriz_camino. 
    #Sus valores finales representan el costo de camino mínimo entre dos nodos. (Si hay un camino)
    #y la secuencia de camino respectivamente.
    numVertices= self.numVertices
    matriz_warshall= np.copy(self.representacionWarshallMatriz())
    matriz_camino= np.copy(self.matrizCaminoInicial())
    for pivote in range(numVertices):
      for i in range(numVertices):
        for j in range(numVertices):
          if(matriz_warshall[i][pivote]+ matriz_warshall[pivote][j] < matriz_warshall[i][j]):
            matriz_warshall[i][j]= matriz_warshall[i][pivote]+ matriz_warshall[pivote][j]
            matriz_camino[i][j]= matriz_camino[pivote][j]

    return matriz_warshall, matriz_camino

#Descripción: función que recibe dos vértices, ésta retornará el costo de camino mínimo entre esos dos vertices
#claro, siempre y cuando haya un camino, en caso de no haber la salida es -1.

  def costocaminoMasCortoEntreDosNodos(self, nodo1, nodo2):
    costoCamino= -1 #representa cuando no hay camino
    matriz_warshall= self.algoritmoWarshall()[0]
    if(matriz_warshall[nodo1][nodo2] != math.inf):
      costoCamino= matriz_warshall[nodo1][nodo2]
    return costoCamino

#Descripción: 

  def caminoMasCortoEntreDosNodos(self,nodo1, nodo2):
    nodoFinal= str(nodo2)
    myPath= ' '
    matriz_caminoMasCorto= self.algoritmoWarshall()[1]
    while(matriz_caminoMasCorto[nodo1][nodo2] != nodo1 and matriz_caminoMasCorto[nodo1][nodo2] != -1):
          myPath+= str(int(matriz_caminoMasCorto[nodo1][nodo2])) + ' -- '
          nodo2= int(matriz_caminoMasCorto[nodo1][nodo2])

    return str(nodo1) + myPath[::-1] + ' -- ' + nodoFinal
    
  

In [ ]:
#Se carga el archivo con el que trabajaremos
!wget https://raw.githubusercontent.com/Paoladevelopment/discretas2/main/grafo3.txt
!wget https://raw.githubusercontent.com/Paoladevelopment/discretas2/main/grafo4.txt
!wget https://raw.githubusercontent.com/Paoladevelopment/discretas2/main/grafo1.txt

In [30]:
#abrirArchivo(): se encarga de abrir el nombre del archivo que se le pase por párametro.
def abrirArchivo(nombre_archivo):
    archivo= open(nombre_archivo, "r")
    return archivo

In [31]:
#guardarInfoArchivoTextoEnUnaLista(): Se encarga de almacenar en una lista la información contenida en el
#archivo de texto, cada posicion de la lista representa una linea del archivo de texto.
#Ejemplo: el contenido del archivo es el siguiente:
'''
5
1
4
0 1 0 7 0
0 0 4 2 0
0 0 0 0 3
0 0 1 0 5
0 0 0 0 0
'''
#la funcion retornaría: ['5', '1', '4', '0 1 0 7 0', '0 0 4 2 0', '0 0 0 0 3', '0 0 1 0 5', '0 0 0 0 0']

def guardarInfoArchivoTextoEnUnaLista(archivo):
  datos= []
  for linea in archivo:
    datos.append(linea.strip('\n'))
  return datos


In [53]:
salir= bool(0)
archivo= None
grafoEjemplo= grafo(0)
while(not salir):
  print('Elije una opción entre las siguientes')
  print('1) Ingresar nombre del archivo y crear grafo')
  print('2) Averiguar el costo mínimo entre dos vértices del grafo ingresado, junto con su \ncamino de aristas')
  print('3) Imprimir matriz de adyacencia, de warshall y de camino final')
  print('4) Imagén del grafo')
  print('5) Salir')
  opcion= int(input('Ingresa una opción: '))
  if(opcion== 1):
    nombre_archivo= input("Ingrese el nombre del archivo: ")
    archivo= abrirArchivo(nombre_archivo)
    datos= guardarInfoArchivoTextoEnUnaLista(archivo)
    grafoEjemplo= grafo(int(datos[0]))
    grafoEjemplo.llenarMatriz(datos[3:])
  elif(opcion==2):
    verticeInicial= int(input('Ingrese el vértice inicial: '))
    verticeFinal= int(input('Ingrese el vértice final: '))

    print('El costo minimo entre : ', verticeInicial, ' y ', verticeFinal, 'es: ', grafoEjemplo.costocaminoMasCortoEntreDosNodos(verticeInicial, verticeFinal))
    print('El camino para llegar desde el vértice inicial al final es: ', grafoEjemplo.caminoMasCortoEntreDosNodos(verticeInicial, verticeFinal))
  elif(opcion== 3):
    print('Matriz de adyacencia del grafo: ')
    print(grafoEjemplo.matrizAdyacencia)
    print()
    print('Matriz de warshall: ')
    print(grafoEjemplo.algoritmoWarshall()[0])
    print('Matriz de caminos final: ')
    print(grafoEjemplo.algoritmoWarshall()[1])
  elif(opcion== 4):
    print('en desarrollo')
  elif(opcion==5):
    salir= bool(1)
  else:
    print('Ingrese una válida opción.')







Elije una opción entre las siguientes
1) Ingresar nombre del archivo y crear grafo
2) Averiguar el costo mínimo entre dos vértices del grafo ingresado, junto con su 
camino de aristas
3) Imprimir matriz de adyacencia, de warshall y de camino final
4) Imagén del grafo
5) Salir
Ingresa una opción: 1
Ingrese el nombre del archivo: grafo1.txt
Elije una opción entre las siguientes
1) Ingresar nombre del archivo y crear grafo
2) Averiguar el costo mínimo entre dos vértices del grafo ingresado, junto con su 
camino de aristas
3) Imprimir matriz de adyacencia, de warshall y de camino final
4) Imagén del grafo
5) Salir
Ingresa una opción: 3
Matriz de adyacencia del grafo: 
[[0 1 0 7 0]
 [0 0 4 2 0]
 [0 0 0 0 3]
 [0 0 1 0 5]
 [0 0 0 0 0]]

Matriz de warshall: 
[[ 0.  1.  4.  3.  7.]
 [inf  0.  3.  2.  6.]
 [inf inf  0. inf  3.]
 [inf inf  1.  0.  4.]
 [inf inf inf inf  0.]]
Matriz de caminos final: 
[[ 0.  0.  3.  1.  2.]
 [-1.  1.  3.  1.  2.]
 [-1. -1.  2. -1.  2.]
 [-1. -1.  3.  3.  2.]
 [-1.